########################
## Experiment Options ##
########################

name: kitti_l1

########################
##### Data Options #####
########################

dataroot: /datad/dgeng/kitti/kitti_512
dataloader: kitti

########################
#### Train Options #####
########################

l1: True

gpu_ids: [0]
nThreads: 4
batchSize: 5
niter: 20

ngf: 32

#######################
#### Test Options #####
#######################

how_many: 100
which_epoch: 20
