########################
## Experiment Options ##
########################

name: toy_mse

########################
##### Data Options #####
########################

bg_path: ./assets/bg.png
obj_path: ./assets/car.png
loadSize: 512

x_offset: .05
y_offset: 0
x_center: .5
y_center: .7

########################
#### Train Options #####
########################

corrwise: False

mse: True

gpu_ids: [0]
nThreads: 0
batchSize: 4

#######################
#### Test Options #####
#######################

how_many: 20
which_epoch: 10
